### ISSUE TITLE
window is not defined - server side

### ISSUE THREAD

**Issue by vargasj** [aurelia/metadata#13]
I was trying to use aurelia DI on a node application and after installing all dependencies I got the following error:

dependency-injection-test/node_modules/aurelia-metadata/dist/commonjs/origin.js:16
if (!window.System) {
     ^
ReferenceError: window is not defined
    at Object.<anonymous> (dependency-injection-test/node_modules/aurelia-metadata/dist/commonjs/origin.js:16:6)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:171:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (dependency-injection-test/node_modules/aurelia-metadata/dist/commonjs/index.js:5:15)
    at Module._compile (module.js:460:26)

After commenting the if I get the following error:

if (!System.forEachModule) {
     ^
ReferenceError: System is not defined
    at Object.<anonymous> (dependency-injection-test/node_modules/aurelia-metadata/dist/commonjs/origin.js:20:6)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:171:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/dependency-injection-test/node_modules/aurelia-metadata/dist/commonjs/index.js:5:15)
    at Module._compile (module.js:460:26)

If I declare a var System = { }; before that if everything works correctly.

I'm running the application with babel-node --stage 0

**Comment by EisenbergEffect** [comment]
We can certainly fix this, but there is a bit of a gap in my knowledge. We need a way to reference the platform "global" from inside an ES6 module. I'm not sure how to do that.... I'll need to research.

**Comment by stoffeastrom** [comment]
@EisenbergEffect Maybe you could do something like this?
```
const IS_NODE = typeof process !== "undefined" && Object.prototype.toString.call( process ) === "[object process]";

var global = IS_NODE ? global : window;

if ( !global.System ) {
  global.System = {};
}
```

**Comment by EisenbergEffect** [comment]
Needed to make a slight variation to that, but looks like it will work :) I'll get the fix into the next release, probably going out Monday.

**Comment by EisenbergEffect** [comment]
Got a fix on this coming in tomorrow releases.
